### ISSUE TITLE
Feature Request: Uploaded file expiry hours/days choice

### ISSUE THREAD

**Issue by ghost** [qorg11/lainsafe#13]
I would like a feature that would let you choose how many hours or days the file will expire, similar to what [Litterbox](https://litterbox.catbox.moe) has.
![litterbox](https://user-images.githubusercontent.com/71349990/93475422-94177600-f8c6-11ea-8396-6e413ab51cef.png)

**Comment by qorg11** [comment]
Server administrators can use [lsd](https://git.kalli.st/czar/lsd) for this. users cannot, i'll work on this

**Comment by qorg11** [comment]
Been thinking on this issue a bit. This would bloat lainsafe a lot, because you'd have to run a lainsafe daemon so it is running always to delete the files.
Not to mention where to stores the hours in which the file will be deleted, i'd have to use a csv, which means i'd have to use another perl module (or use awk inside perl, which is evil).

I don't think I can work on this unless I make a lainsafe fork.
